# fly.toml app configuration file generated for pcola-crud-api on 2024-06-17T18:23:31-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pcola-crud-api'
primary_region = 'atl'

[build]
  [build.args]
    GO_VERSION = '1.22.1'

[env]
  PORT = '8080'

[http_service]
  internal_port = 1323
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
